# url = jdbc:gbasedbt-sqli://192.168.80.215:9088/testdb:SERVER_LOCALE=zh_CN.utf8;DB_LOCALE=zh_CN.utf8;CLIENT_LOCALE=zh_CN.utf8;SQMODE=mysql;IFX_LOCK_MODE_WAIT=10;APPENDISAM=true;LOBCACHE=-1;FET_BUF_SIZE=1048576
url = jdbc:gbasedbt-sqli://192.168.0.211:23215/testdb:SERVER_LOCALE=zh_CN.utf8;DB_LOCALE=zh_CN.utf8;CLIENT_LOCALE=zh_CN.utf8;SQMODE=Oracle;IFX_LOCK_MODE_WAIT=10;APPENDISAM=true;LOBCACHE=-1;FET_BUF_SIZE=1048576
user = gbasedbt
pass = GBase123$%
